// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeTrackerModelLib.Models
{
    [Table("DailyWorkLocation")]
    public partial class DailyWorkLocation
    {
        [Key]
        public int WorkLocationId { get; set; }
        public int? UserId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string LocationType { get; set; }
        public int? WorkboothId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("DailyWorkLocations")]
        public virtual User User { get; set; }
        [ForeignKey("WorkboothId")]
        [InverseProperty("DailyWorkLocations")]
        public virtual Workbooth Workbooth { get; set; }
    }
}