// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeTrackerModelLib.Models
{
    public partial class JobPosition
    {
        public JobPosition()
        {
            UserProfiles = new HashSet<UserProfile>();
        }

        [Key]
        public int JobPositionId { get; set; }
        [Required]
        [StringLength(255)]
        public string Position { get; set; }

        [InverseProperty("JobPosition")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}