// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TimeTrackerModelLib.Models
{
    [Table("Workbooth")]
    public partial class Workbooth
    {
        public Workbooth()
        {
            DailyWorkLocations = new HashSet<DailyWorkLocation>();
        }

        [Key]
        public int WorkboothId { get; set; }
        public bool? IsAvailable { get; set; }

        [InverseProperty("Workbooth")]
        public virtual ICollection<DailyWorkLocation> DailyWorkLocations { get; set; }
    }
}